### PR TITLE
A demo for Vue (an array of objects for hot-column)

### PR DESCRIPTION
**Pull request by scarletfog**
### Context
Add a similar demo as for React https://github.com/handsontable/docs/pull/144/files

### Types of changes
- [x] Improvement (better description, more examples etc.)

### Related issue(s):
1. https://github.com/handsontable/docs/issues/151

### CODE REVIEW

**Review by pnowak — APPROVED** [review]
Everything seems ok. 
I'm wondering only about the position of this new example. I think that the second position is better, right behind the simplest one.

**Review by AMBudnik — APPROVED** [review]
I see my demo :) I wouldn't say that the data is interesting (only numbers) but it shows the case so I guess that we can use it.

**Comment by scarletfog** [comment]
@pnowak @AMBudnik can you please check again? I applied your suggestions.

**Review by pnowak — APPROVED** [review]
👌 Perfect.

**Review by AMBudnik — APPROVED** [review]
That data is way better than the one that I proposed 👍

**Pull request merged**
