### PR TITLE
Remove dangling angle bracket

### PR DESCRIPTION
**Pull request by user501254**

### CODE REVIEW

**Comment by AMBudnik** [comment]
Thank you for sharing the typo fix. However, even for the single changes, we need to have your permission to use them. Can you please sign the [CLA](https://docs.google.com/forms/d/e/1FAIpQLScpMq4swMelvw3-onxC8Jl29m0fVp5hpf7d1yQVklqVjGjWGA/viewform?c=0&w=1)?

**Comment by user501254** [comment]
Done.

**Comment by AMBudnik** [comment]
Hi @user501254 

your PR got merged. Again, thank you for sharing 👍

**Comment by AMBudnik** [comment]
Hi @user501254 

I am sorry but there seems to the a problem with your signature on the CLA document (I do not see your Github nickname of the list). Have you signed the document for any other nickname? Would you be able to place the signature for your current nickname?

Here's the CLA https://docs.google.com/forms/d/e/1FAIpQLScpMq4swMelvw3-onxC8Jl29m0fVp5hpf7d1yQVklqVjGjWGA/viewform?c=0&w=1

**Comment by AMBudnik** [comment]
Hi @user501254 

your PR got merged. Again, thank you for sharing 👍

**Pull request merged**
