### PR TITLE
Update data-validation.html

### PR DESCRIPTION
**Pull request by multinerd**
### Types of changes

- [x] Bug fix (any error in documentation i.e. wrong: wording, code, links, pictures, etc.)
- [ ] Improvement (better description, more examples etc.)
- [ ] Misc (any other change)

### Related issue(s):
1.
2.
3.

### CODE REVIEW

**Comment by AMBudnik** [comment]
Hi @multinerd 

Thank you for sharing the change. 

We may clone it and publish or we can make you a contributor. But then we require to [sign our CLA](https://docs.google.com/forms/d/e/1FAIpQLScpMq4swMelvw3-onxC8Jl29m0fVp5hpf7d1yQVklqVjGjWGA/viewform?c=0&w=1).

**Comment by multinerd** [comment]
Clone and publish please.

**Comment by AMBudnik** [comment]
Thank you @multinerd 
@scarletfog please create a new PR based on this one. Thanks!

**Comment by AMBudnik** [comment]
This change has been moved to https://github.com/handsontable/docs/pull/264 
Again, thank you for your feedback @multinerd

**Pull request closed without merging**
