### PR TITLE
Update principles.html

### PR DESCRIPTION
**Pull request by oliv3**
s/need/needs

### CODE REVIEW

**Comment by AMBudnik** [comment]
Thanks for spotting that @oliv3 !

**Comment by AMBudnik** [comment]
Sorry, but it looks like we do not have a CLA signed by you @oliv3 
Could you sign it, please? Only then we will be able to pull the changes.

**Comment by oliv3** [comment]
How do I do that ?

**Comment by AMBudnik** [comment]
Here is our CLA https://docs.google.com/forms/d/e/1FAIpQLScpMq4swMelvw3-onxC8Jl29m0fVp5hpf7d1yQVklqVjGjWGA/viewform?c=0&w=1
As soon as you give us a permission to use this PR by signing CLA I will be able to pull the code

**Comment by oliv3** [comment]
Done!

**Comment by AMBudnik** [comment]
Thank you @oliv3

**Pull request merged**
